version: "3.9"
services:
  authservice:
    image: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.22
    container_name: authservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=34.31.6.243;Port=5432;Database=xyz_authdb;Username=postgres;Password=Postgres123$;
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"
    networks:
      - fuel-net
    volumes:
      - ./XYZ.AuthService:/app
    working_dir: /app
    command: |
      sh -c "
        apk add --no-cache protobuf-dev gcompat &&
        dotnet restore &&
        dotnet run --urls http://*:5000
      "

  driversservice:
    image: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.22
    container_name: driversservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=34.31.6.243;Port=5432;Database=xyz_driversdb;Username=postgres;Password=Postgres123$;
      - ASPNETCORE_URLS=http://*:5001
    ports:
      - "5001:5001"
    networks:
      - fuel-net
    volumes:
      - ./XYZ.DriversService:/app
    working_dir: /app
    command: |
      sh -c "
        apk add --no-cache protobuf-dev gcompat &&
        dotnet restore &&
        dotnet run --urls http://*:5001
      "

  vehiclesservice:
    image: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.22
    container_name: vehiclesservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=34.31.6.243;Port=5432;Database=xyz_vehiclesdb;Username=postgres;Password=Postgres123$;
      - ASPNETCORE_URLS=http://*:5002
    ports:
      - "5002:5002"
    networks:
      - fuel-net
    volumes:
      - ./XYZ.VehiclesService:/app
    working_dir: /app
    command: |
      sh -c "
        apk add --no-cache protobuf-dev gcompat &&
        dotnet restore &&
        dotnet run --urls http://*:5002
      "

  routesservice:
    image: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.22
    container_name: routesservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=34.31.6.243;Port=5432;Database=xyz_routesdb;Username=postgres;Password=Postgres123$;
      - ASPNETCORE_URLS=http://*:5003
    ports:
      - "5003:5003"
    networks:
      - fuel-net
    volumes:
      - ./XYZ.RoutesService:/app
    working_dir: /app
    command: |
      sh -c "
        apk add --no-cache protobuf-dev gcompat &&
        dotnet restore &&
        dotnet run --urls http://*:5003
      "

  fuelservice:
    image: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.22
    container_name: fuelservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=34.31.6.243;Port=5432;Database=xyz_fueldb;Username=postgres;Password=Postgres123$;
      - ASPNETCORE_URLS=http://+:5004
    ports:
      - "5004:5004"
    networks:
      - fuel-net
    volumes:
      - ./XYZ.FuelService:/app
    working_dir: /app
    command: |
      sh -c "
        apk add --no-cache protobuf-dev gcompat &&
        dotnet restore &&
        dotnet run --urls http://+:5004
      "

  apigateway:
    image: mcr.microsoft.com/dotnet/sdk:9.0-alpine3.22
    container_name: apigateway
    depends_on:
      - authservice
      - driversservice
      - vehiclesservice
      - routesservice
      - fuelservice
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:80
    ports:
      - "8080:80"
    networks:
      - fuel-net
    volumes:
      - ./XYZ.ApiGateway:/app
    working_dir: /app
    command: |
      sh -c "
        apk add --no-cache protobuf-dev gcompat &&
        dotnet restore &&
        dotnet run --urls http://*:80
      "

networks:
  fuel-net:
    driver: bridge
