version: "3.9"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - fuel-net

  authservice:
    build:
      context: ./XYZ.AuthService
      dockerfile: Dockerfile
    container_name: authservice
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=XYZ_AuthDB;User Id=sa;Password=Your_password123;TrustServerCertificate=true;
    ports:
      - "5000:5000"
    networks:
      - fuel-net

  driversservice:
    build:
      context: ./XYZ.DriversService
      dockerfile: Dockerfile
    container_name: driversservice
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=XYZ_DriversDB;User Id=sa;Password=Your_password123;TrustServerCertificate=true;
    ports:
      - "5002:80"
    networks:
      - fuel-net


networks:
  fuel-net:
    driver: bridge
