version: "3.9"
services:
  postgres:
    image: postgres:13.22-alpine3.22
    container_name: postgres
    environment:
      POSTGRES_DB: "authdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - fuel-net

  authservice:
    image: authservice-grpc-http2:latest
    container_name: authservice
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
    networks:
      - fuel-net

networks:
  fuel-net:
    driver: bridge
