version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - fuel-net
    volumes:
      - ./scripts/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  authservice:
    build:
      context: ./XYZ.AuthService
      dockerfile: Dockerfile
    container_name: authservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=xyz_authdb;Username=postgres;Password=postgres;
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"
    networks:
      - fuel-net

  driversservice:
    build:
      context: ./XYZ.DriversService
      dockerfile: Dockerfile
    container_name: driversservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=xyz_driversdb;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://*:5001
    ports:
      - "5001:5001"
    networks:
      - fuel-net

  vehiclesservice:
    build: ./XYZ.VehiclesService
    container_name: vehiclesservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=xyz_vehiclesdb;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://*:5002
    ports:
      - "5002:5002"
    networks:
      - fuel-net

  routesservice:
    build:
      context: ./XYZ.RoutesService
      dockerfile: Dockerfile
    container_name: routesservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=xyz_routesdb;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://*:5003
    ports:
      - "5003:5003"
    networks:
      - fuel-net

  fuelservice:
    build:
      context: ./XYZ.FuelService
      dockerfile: Dockerfile
    container_name: fuelservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=xyz_fueldb;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://+:5004
    ports:
      - "5004:5004"
    networks:
      - fuel-net

networks:
  fuel-net:
    driver: bridge
