// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XYZ.FuelService.Infrastructure.Persistence;

#nullable disable

namespace XYZ.FuelService.Migrations
{
    [DbContext(typeof(FuelDbContext))]
    partial class FuelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XYZ.FuelService.Domain.Entities.FuelRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ActualLiters")
                        .HasColumnType("double precision")
                        .HasColumnName("actual_liters");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_km");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer")
                        .HasColumnName("driver_id");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<double>("EstimatedLiters")
                        .HasColumnType("double precision")
                        .HasColumnName("estimated_liters");

                    b.Property<int>("RouteId")
                        .HasColumnType("integer")
                        .HasColumnName("route_id");

                    b.Property<string>("TipoMaquinaria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_maquinaria");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("VehiclePlaca")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vehicle_placa");

                    b.HasKey("Id")
                        .HasName("pk_fuel_records");

                    b.ToTable("fuel_records", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
